
const QUOTES = [
    { text: "The stock market is a device for transferring money from the impatient to the patient.", author: "Warren Buffett" },
    { text: "Price is what you pay. Value is what you get.", author: "Warren Buffett" },
    { text: "Time in the market beats timing the market.", author: "Ken Fisher" },
];

const STORIES = {
    'all-news': [
        {
            lead: true,
            tag: 'MARKETS',
            tagColor: 'mint',
            source: 'Business Standard',
            sourceUrl: 'https://business-standard.com',
            headline: 'Nifty, Sensex Bleed 1.5% — MSCI Rebalancing Hits Harder Than Expected',
            subline: 'Nifty 50 closes at 23,547.75, down 359 pts. Sensex at 74,775. Three-day losing streak driven by FII selling, MSCI churn, and below-normal monsoon forecast.',
            body: 'FIIs sold ₹4,200+ Cr on Friday alone — MSCI semi-annual rebalancing was the trigger. Reliance, HDFC Bank, and ICICI Bank took the biggest hits. The monsoon forecast at 90% of LPA is spooking agri and rural consumption plays. Short-term pain fr, but fundamentals haven\'t changed.',
            time: '3:45 PM',
        },
        {
            tag: 'RBI',
            tagColor: 'cyan',
            source: 'Mint',
            sourceUrl: 'https://livemint.com',
            headline: 'RBI Deploys $5B USD/INR Swap to Defend Rupee at ₹95',
            subline: 'Reserve Bank intervenes with a $5B buy/sell swap auction as rupee hits record lows near ₹97. Move injects liquidity and shores up the currency.',
            body: 'The rupee has been getting cooked — down 12%+ YTD as FII outflows and Strait of Hormuz energy risk pile on. RBI\'s $5B swap is a strong signal that they\'ll defend the ₹95 level. USD/INR closed at ₹84.96 on Friday. Watch the RBI\'s FX reserve burn rate ngl.',
            time: '11:30 AM',
        },
        {
            tag: 'MACRO',
            tagColor: 'cyan',
            source: 'New Indian Express',
            sourceUrl: 'https://newindianexpress.com',
            headline: 'Finance Ministry: India\'s Outlook Is "Cautious Resilience" — Here\'s What That Means',
            subline: 'DEA Monthly Economic Review flags Strait of Hormuz risk, rising WPI, weak monsoon, and rupee depreciation as key near-term threats to growth.',
            body: 'Retail inflation at 3.48% in April is contained — but WPI is creeping up and could pass through to CPI by Q2. The four-letter word nobody\'s saying: stagflation risk. RBI raised FY27 GDP outlook to 6.2–6.5% at the May MPC, but kept the repo steady. Cautious is the right word.',
            time: '10:00 AM',
        },
        {
            tag: 'VC FUNDING',
            tagColor: 'purple',
            source: 'Economic Times',
            sourceUrl: 'https://economictimes.com',
            headline: 'Rapido Closes $240M Round Led by Prosus — Bike-Taxi War is On',
            subline: 'Rapido raises $240M from Prosus, WestBridge, and Accel. India startup funding up 37% YoY in May 2026 to $1.1B total.',
            body: 'Prosus dropped the biggest India startup check of May 2026 on Rapido. The bike-taxi and auto category is 4x larger than cabs in terms of rides — Rapido has 60M+ users and the unit economics are now positive. Ola and Uber have been sleeping on this category. Late-stage funding at 81% of total May deal value — the recovery is real.',
            time: '9:00 AM',
        },
        {
            tag: 'REGULATION',
            tagColor: 'gold',
            source: 'SEBI',
            sourceUrl: 'https://sebi.gov.in',
            headline: 'SEBI Overhauls Mutual Fund Framework — New MF Regulations 2026 Live',
            subline: 'SEBI (Mutual Funds) Regulations 2026 effective April 1. Nomination mandatory for single-holder demat accounts from September 1. MCR format revised.',
            body: 'SEBI dropped a full MF rulebook overhaul. Single-holder demat accounts must have a nominee from Sept 1 or explicitly opt out — this plugs a massive unclaimed asset gap. Educational trading simulators using live market data are now under stricter SEBI oversight. AI-driven algo strategies need exchange validation.',
            time: '8:30 AM',
        },
        {
            tag: 'GLOBAL MACRO',
            tagColor: 'cyan',
            source: 'Bloomberg',
            sourceUrl: 'https://bloomberg.com',
            headline: 'Fed Holds at 3.50–3.75%, Signals No Cuts Until Late 2026',
            subline: 'April FOMC keeps rates steady. Committee members debated signaling possible hikes as inflation stays above 2%. Rate cut expectations pushed to December at earliest.',
            body: 'The Fed is stuck between a rock and a tariff. Sticky inflation + $700/household tariff hit = no room to cut. Some hawks on the committee even floated rate hike signaling. This is brutal for EM flows — the dollar stays strong, which means more pressure on the rupee. No cap, higher for longer is the new normal.',
            time: '7:15 AM',
        },
        {
            tag: 'M&A',
            tagColor: 'mint',
            source: 'The Logical Indian',
            sourceUrl: 'https://thelogicalindian.com',
            headline: 'Sun Pharma Acquires Organon\'s India Business — Specialty Pharma Play',
            subline: 'Sun Pharma\'s acquisition of Organon India strengthens its branded generics and women\'s health portfolio. Deal valued at ~$380M.',
            body: 'Sun Pharma is doubling down on the specialty-and-branded-generics thesis. Organon\'s India portfolio adds ₹1,800 Cr revenue and a 2,000-strong MR field force. The women\'s health segment is underpenetrated and growing at 18% CAGR. This deal is lowkey one of the smarter pharma moves of 2026.',
            time: '6:45 AM',
        },
        {
            tag: 'TRADE',
            tagColor: 'slate',
            source: 'Financial Times',
            sourceUrl: 'https://ft.com',
            headline: 'Global Trade Growth Slows to 1.9% — Supply Chains Rewiring Fast',
            subline: 'WTO downgrades 2026 global trade growth forecast from 4.6% to 1.9%. Tariff uncertainty and US-China tensions driving supply chain fragmentation.',
            body: 'The tariff war collateral damage is hitting global trade hard. India is actually a net beneficiary — supply chain diversification from China is routing through India-based manufacturing. The India-US trade deal negotiations (targeting $500B by 2030) are back on the table. Period.',
            time: '6:00 AM',
        },
    ],

    'tech-specs': [
        {
            lead: true,
            tag: 'AI',
            tagColor: 'purple',
            source: 'TechCrunch',
            sourceUrl: 'https://techcrunch.com',
            headline: '🤖 OpenAI Enterprise Revenue Hits $8B ARR — SaaS Is Shook',
            subline: 'OpenAI crosses $8B ARR milestone with Enterprise tier growing 240% YoY — now 92% of Fortune 500.',
            body: 'OpenAI really went from "cool chatbot" to "enterprise SaaS monster" in 18 months no cap. GPT-5 Enterprise with custom fine-tuning is the moat play. Companies paying $60/seat/month is lowkey printing money. Microsoft\'s 49% stake looking more fire by the quarter.',
            time: '7:00 AM',
        },
        {
            tag: 'CLOUD',
            tagColor: 'purple',
            source: 'Business Standard',
            sourceUrl: 'https://business-standard.com',
            headline: '☁️ AWS India Revenue Crosses $5B — Data Center Boom Bussin',
            subline: 'Amazon Web Services India ops hit $5B revenue run-rate with 3 new availability zones launching in Hyderabad.',
            body: 'AWS building data centers in India like they\'re playing SimCity fr. The $12.7B capex commitment through 2030 is real. Indian enterprises moving to cloud at 35% CAGR and AWS wants all of it. Azure and GCP are lowkey sweating.',
            time: '7:30 AM',
        },
        {
            tag: 'SAAS',
            tagColor: 'purple',
            source: 'Inc42',
            sourceUrl: 'https://inc42.com',
            headline: '💻 Freshworks Hits $900M ARR — IPO Premium Gang',
            subline: 'Freshworks Q1 FY27 ARR hits $900M with AI agent suite driving 45% of new bookings.',
            body: 'Girish Mathrubootham really built different ngl. The "Freddy AI" agent suite is replacing Zendesk at enterprise accounts left and right. Net dollar retention back above 115%. Indian SaaS representing on the global stage, period.',
            time: '8:00 AM',
        },
        {
            tag: 'AUTOMATION',
            tagColor: 'purple',
            source: 'TechCrunch',
            sourceUrl: 'https://techcrunch.com',
            headline: '⚙️ UiPath Acquires AI Startup for $780M — Agentic Play',
            subline: 'UiPath acquires Adept AI in $780M all-cash deal to build autonomous enterprise agents.',
            body: 'RPA + AI agents = the real endgame. UiPath just bought Adept to make their bots actually intelligent instead of just following scripts. The "agentic automation" market is projected at $42B by 2028. Lowkey the smartest M&A in enterprise software this year.',
            time: '6:30 AM',
        },
        {
            tag: 'AI INFRA',
            tagColor: 'cyan',
            source: 'Reuters',
            sourceUrl: 'https://reuters.com',
            headline: '🔥 NVIDIA H200 Demand "Insane" — Jensen at Computex',
            subline: 'Jensen Huang reveals H200 backlog extends to Q1 2027 — raises FY27 data center guidance to $95B.',
            body: 'Jensen literally showed up in a leather jacket and said "we can\'t make enough GPUs" fr. Sovereign AI demand from India, UAE, and Japan is the new growth vector. NVIDIA\'s data center revenue is now 4x their gaming business. Stock pumped 6% after-hours.',
            time: '9:00 AM',
        },
        {
            tag: 'INDIA TECH',
            tagColor: 'mint',
            source: 'VCCircle',
            sourceUrl: 'https://vccircle.com',
            headline: '🇮🇳 Zerodha Launches AI Trading Co-Pilot — First in India',
            subline: 'Zerodha unveils "Kite AI" — an LLM-powered trading assistant for retail investors, free for all users.',
            body: 'Nithin Kamath really said "democratize investing even harder." Kite AI does portfolio analysis, options strategy suggestions, and earnings call summarization. Built in-house with a fine-tuned open-source model. No subscription fee — classic Zerodha move. Groww and Upstox punching air.',
            time: '8:15 AM',
        },
        {
            tag: 'CYBERSEC',
            tagColor: 'red',
            source: 'Bloomberg',
            sourceUrl: 'https://bloomberg.com',
            headline: '🛡️ CrowdStrike ARR Hits $4.5B — Security Spending GOAT',
            subline: 'CrowdStrike crosses $4.5B ARR with 83% gross margin — Falcon platform now has 28 modules.',
            body: 'Post-outage recovery arc is complete ngl. CrowdStrike just proved that even after bricking half the world\'s Windows machines, enterprises still can\'t quit them. The platform play is too sticky. Net retention at 120%+ and the SOC automation module is bussin.',
            time: '7:45 AM',
        },
    ],

    'energy-grid': [
        {
            lead: true,
            tag: 'GREEN ENERGY',
            tagColor: 'gold',
            source: 'Economic Times',
            sourceUrl: 'https://economictimes.com',
            headline: '⚡ NTPC Green Energy Bags 4.2 GW Solar — Largest Order Ever',
            subline: 'NTPC Green Energy wins 4.2 GW solar capacity auction at ₹2.54/unit — ₹18,000 crore project pipeline.',
            body: 'NTPC Green really said "we\'re the new solar kings" fr. 4.2 GW is absolutely massive — that\'s like powering 3 million homes. The ₹2.54/unit tariff is barely above thermal cost parity. Stock up 4.7% on the news. India\'s 500 GW renewable target by 2030 looking more real every day.',
            time: '7:00 AM',
        },
        {
            tag: 'OIL & GAS',
            tagColor: 'gold',
            source: 'Reuters',
            sourceUrl: 'https://reuters.com',
            headline: '🛢️ Brent Crude Slides to $68 — OPEC+ Cut Extension Fails',
            subline: 'Brent crude falls 3.2% to $68.40/bbl after OPEC+ fails to agree on production cut extension beyond September.',
            body: 'OPEC+ literally can\'t agree on anything rn. Saudi wants deeper cuts, UAE wants higher baseline, Russia doing Russia things. The $68 handle is bearish for oil producers but lowkey bullish for Indian refiners like RIL and BPCL. OMCs vibing with cheaper crude.',
            time: '8:30 AM',
        },
        {
            tag: 'POWER INFRA',
            tagColor: 'gold',
            source: 'Mint',
            sourceUrl: 'https://livemint.com',
            headline: '🔌 Power Grid Corp Wins ₹12,000 Cr Transmission Package',
            subline: 'Power Grid Corporation wins mega transmission package for Rajasthan-Gujarat RE corridor — largest single TBCB award.',
            body: 'Power Grid Corp is lowkey the backbone of India\'s energy transition and nobody talks about it. This ₹12K crore transmission corridor will evacuate 8 GW of renewable power from Rajasthan. Order book now at ₹45,000 crore. The stock is a compounding machine fr.',
            time: '6:45 AM',
        },
        {
            tag: 'SOLAR',
            tagColor: 'gold',
            source: 'Business Standard',
            sourceUrl: 'https://business-standard.com',
            headline: '☀️ Adani Green Commissions 2 GW Khavda Project Phase',
            subline: 'Adani Green Energy commissions 2 GW of the 30 GW Khavda hybrid park — world\'s largest renewable energy site.',
            body: 'The Khavda project is genuinely insane in scale ngl. 30 GW planned on a single site in Gujarat\'s Kutch district — that\'s bigger than most countries\' total RE capacity. This 2 GW phase brings total operational capacity to 14.2 GW. Stock ripped 3.1% on commissioning news.',
            time: '8:00 AM',
        },
        {
            tag: 'EV',
            tagColor: 'mint',
            source: 'Economic Times',
            sourceUrl: 'https://economictimes.com',
            headline: '🔋 Tata Motors EV Sales Cross 10K/Month — First Indian OEM',
            subline: 'Tata Motors sells 10,247 EVs in May 2026 — Nexon EV and Curvv EV drive 78% of volume.',
            body: 'Tata Motors EV game is actually bussin fr. First Indian OEM to cross 10K monthly EV sales. Curvv EV at ₹17.5 lakh is the sweet spot the market needed. Charging infra still mid tho — Tata Power has only 8,500 stations vs the 25K needed. Baby steps.',
            time: '9:00 AM',
        },
        {
            tag: 'NUCLEAR',
            tagColor: 'cyan',
            source: 'Bloomberg',
            sourceUrl: 'https://bloomberg.com',
            headline: '⚛️ India Signs $14B Nuclear Deal with France for 6 Reactors',
            subline: 'India-France finalize Jaitapur nuclear plant deal — 6 EPR reactors, 9.6 GW capacity, commissioning from 2034.',
            body: 'The Jaitapur deal has been in limbo for literally 15 years and they finally closed it. 9.6 GW of nuclear is massive — that\'s baseload power that doesn\'t depend on weather. EDF building it, NPCIL operating it. Nuclear stocks (likely beneficiaries: L&T, BHEL) pumped hard.',
            time: '7:30 AM',
        },
    ],

    'stocks-arena': [
        {
            lead: true,
            tag: 'MARKETS',
            tagColor: 'mint',
            source: 'CNBC-TV18',
            sourceUrl: 'https://cnbctv18.com',
            headline: '📊 Nifty Closes Above 26,100 — New ATH Szn Incoming?',
            subline: 'Nifty 50 ends at 26,142 (+0.87%) led by HDFC Bank, Reliance, and ICICI Bank — FII net buyers for 8th straight session.',
            body: 'Bulls are absolutely feasting rn no cap. FIIs bought ₹4,200 crore today and DIIs added another ₹1,800 crore. Broad market breadth was fire — advance/decline at 3:1. Mid-cap index also hit ATH. The 26,500 level is the next resistance and bears are running out of excuses fr.',
            time: '3:45 PM',
        },
        {
            tag: 'LARGE CAP',
            tagColor: 'mint',
            source: 'Economic Times',
            sourceUrl: 'https://economictimes.com',
            headline: '🏦 HDFC Bank Crosses ₹14L Cr Mcap — M-cap King Again',
            subline: 'HDFC Bank market cap hits ₹14.2 lakh crore at ₹1,890/share — reclaims top spot from RIL.',
            body: 'HDFC Bank really said "we\'re back on top" after the post-merger digestion phase. NII growth at 8.2% QoQ, CASA ratio stabilizing at 38%, and the merger cost synergies are finally showing up. Analysts have ₹2,100 target consensus. The most owned stock in India fr.',
            time: '2:30 PM',
        },
        {
            tag: 'EARNINGS',
            tagColor: 'mint',
            source: 'Mint',
            sourceUrl: 'https://livemint.com',
            headline: '🎯 Bajaj Finance Q1 PAT Up 22% — AUM Crosses ₹4L Cr',
            subline: 'Bajaj Finance reports Q1 FY27 PAT of ₹4,280 crore, AUM at ₹4.12 lakh crore — new customer adds at 4.8M.',
            body: 'Bajaj Finance compounding machine goes brr. AUM crossed ₹4 lakh crore with NIM stable at 10.2%. The fintech distribution channel now accounts for 42% of new loans. Asset quality pristine — GNPA at 0.87%. This stock is what "quality premium" means, period.',
            time: '10:00 AM',
        },
        {
            tag: 'ANALYST CALL',
            tagColor: 'purple',
            source: 'Goldman Sachs',
            sourceUrl: 'https://goldmansachs.com',
            headline: '📋 Goldman Upgrades L&T to "Conviction Buy" — ₹4,800 TP',
            subline: 'Goldman Sachs upgrades L&T with ₹4,800 target (28% upside) citing ₹5.2L crore order book and infra capex cycle.',
            body: 'Goldman really said L&T is the best way to play India\'s infra buildout and they\'re not wrong. Order inflow at ₹78,000 crore in Q4 alone is absolutely mental. The Saudi Arabia and Middle East projects pipeline is the kicker nobody\'s pricing in. Conviction Buy = Goldman\'s highest rating fr.',
            time: '8:30 AM',
        },
        {
            tag: 'SECTORAL',
            tagColor: 'gold',
            source: 'CNBC-TV18',
            sourceUrl: 'https://cnbctv18.com',
            headline: '💊 Pharma Index Rips 2.3% — US Generic Pipeline Is Loaded',
            subline: 'Nifty Pharma up 2.3% led by Sun Pharma (+3.8%) and Dr. Reddy\'s (+2.9%) on strong US FDA pipeline updates.',
            body: 'Indian pharma having a moment fr. Sun Pharma got 4 ANDA approvals in May alone, and Dr. Reddy\'s just launched a complex generic worth $600M in the US. The biosimilar wave in 2027 is the next big catalyst. Pharma was the laggard sector all year — this rotation might have legs.',
            time: '1:15 PM',
        },
        {
            tag: 'MID CAP',
            tagColor: 'cyan',
            source: 'Economic Times',
            sourceUrl: 'https://economictimes.com',
            headline: '🚀 Dixon Technologies 52-Week High — Apple Play Is Real',
            subline: 'Dixon Technologies hits ₹16,800 (52W high) on reports of expanded Apple iPhone assembly contract for FY27.',
            body: 'Dixon went from "random EMS company" to "Apple\'s India manufacturing partner" and the market is pricing it in hard. The iPhone assembly revenue alone could be ₹15,000 crore by FY28. Add Samsung, Xiaomi, and Google Pixel — this is India\'s Foxconn moment. Ngl the valuation at 65x PE is spicy tho.',
            time: '11:45 AM',
        },
        {
            tag: 'FII FLOWS',
            tagColor: 'mint',
            source: 'NSDL',
            sourceUrl: 'https://nsdl.co.in',
            headline: '💸 FIIs Net Buyers of ₹28,000 Cr in May — Trend Reversal',
            subline: 'Foreign institutional investors turn net buyers with ₹28,400 crore inflow in May 2026 — strongest month since Jan 2024.',
            body: 'FIIs are BACK baby. After selling ₹1.2 lakh crore in Oct-Dec 2025, they\'re finally rotating back into India. The weak dollar + India GDP beat + stable rupee is the trifecta. Financial services and IT got the most FII love. DII dominance era might be ending, but that\'s actually healthy for market depth.',
            time: '4:00 PM',
        },
    ],

    'metal-shine': [
        {
            lead: true,
            tag: 'GOLD',
            tagColor: 'yellow',
            source: 'World Gold Council',
            sourceUrl: 'https://gold.org',
            headline: '🥇 Gold Touches $2,780 — Central Banks Still Hoarding',
            subline: 'Gold at $2,780/oz up 0.6% — central bank buying at 290 tonnes in Q1 2026, led by China and India.',
            body: 'Gold really said "I don\'t care about your rate hike fears" and kept running. Central banks bought 290 tonnes in Q1 alone — that\'s insane accumulation. China added 18 tonnes, India 12 tonnes, Turkey 8 tonnes. The de-dollarization trade is structural, not cyclical. No cap, gold at $3,000 by year-end is looking more likely every week.',
            time: '7:00 AM',
        },
        {
            tag: 'SILVER',
            tagColor: 'yellow',
            source: 'Reuters',
            sourceUrl: 'https://reuters.com',
            headline: '🥈 Silver Breaks $38 — Industrial Demand + Solar = 🔥',
            subline: 'Silver at $38.20/oz, up 1.4% — solar panel demand and AI data center power needs driving structural deficit.',
            body: 'Silver is lowkey the most underrated trade rn fr. Solar panels use 20% more silver per unit than 5 years ago, and global solar installations are up 45% YoY. Add the AI data center power demand and you\'ve got a structural supply deficit. Gold-silver ratio at 72x still says silver is cheap relative to gold. The $40 break is coming.',
            time: '7:30 AM',
        },
        {
            tag: 'COPPER',
            tagColor: 'gold',
            source: 'Bloomberg',
            sourceUrl: 'https://bloomberg.com',
            headline: '🟤 Copper Hits $10,200/ton — Dr. Copper Says Economy Fine',
            subline: 'LME copper at $10,200/ton, up 0.8% — EV + grid demand creating 500K tonne annual deficit.',
            body: 'They call copper "Dr. Copper" because it has a PhD in economics and it\'s saying the global economy is healthier than the bears think. EV wiring uses 4x more copper than ICE vehicles. Add the global grid upgrade cycle and you\'ve got demand that mines literally can\'t keep up with. Vedanta and Hindalco are proxy plays.',
            time: '8:00 AM',
        },
        {
            tag: 'MCX',
            tagColor: 'gold',
            source: 'MCX India',
            sourceUrl: 'https://mcxindia.com',
            headline: '📊 MCX Gold at ₹73,560/10g — Akshaya Tritiya Effect',
            subline: 'MCX gold futures at ₹73,560/10g — physical demand spike post-Akshaya Tritiya season.',
            body: 'Indian gold demand is bussin rn. Akshaya Tritiya buying was 22% higher YoY and jewelers are restocking hard. Import duty cut to 6% last budget is keeping prices competitive vs international. ETF inflows into gold funds at ₹2,400 crore in May. Gold SIPs are lowkey the smartest retail trade.',
            time: '8:30 AM',
        },
        {
            tag: 'COMMODITY',
            tagColor: 'gold',
            source: 'CME Group',
            sourceUrl: 'https://cmegroup.com',
            headline: '📈 Aluminum Rallies 4% on China Smelter Curtailments',
            subline: 'LME aluminum at $2,680/ton after China orders 800K tonnes of smelting capacity offline for power rationing.',
            body: 'China cutting aluminum smelting capacity because their hydro reservoirs are low = instant price spike. This happens every summer but the market still gets surprised every time ngl. Hindalco and Nalco are the Indian plays. Aluminum demand for EVs and packaging keeps growing. The structural story is solid.',
            time: '9:00 AM',
        },
        {
            tag: 'OUTLOOK',
            tagColor: 'yellow',
            source: 'Goldman Sachs',
            sourceUrl: 'https://goldmansachs.com',
            headline: '🔮 Goldman: "Buy Gold, Silver, Copper" — Super Cycle Call',
            subline: 'Goldman Sachs metals team calls for commodities super cycle — gold $3,200, silver $45, copper $12,000 by end-2027.',
            body: 'Goldman\'s commodity desk just dropped a banger report fr. Their thesis: electrification + AI power demand + de-dollarization = multi-year metals bull run. They\'re most bullish on silver (industrial + monetary demand overlap) and copper (green transition bottleneck). The "sell commodities, buy tech" trade might be dead.',
            time: '6:30 AM',
        },
    ],

    'vc-inflow': [
        {
            lead: true,
            tag: 'LATE STAGE',
            tagColor: 'purple',
            source: 'YourStory',
            sourceUrl: 'https://yourstory.com',
            headline: '💸 Anveshan Raises ₹121 Cr from Vertex & Titan Capital',
            subline: 'Anveshan secures ₹121 crore to expand its D2C food and agriculture footprint.',
            body: 'Funding in Indian startups hit a slow week, but Anveshan broke the silence raising ₹121 crore from top tier investors including Vertex Ventures and Titan Capital. The D2C food brand is scaling up aggressive offline expansion.',
            time: '9:00 AM',
            vc: { stage: 'Growth', investors: 'Vertex Ventures, Titan Capital, Aman Gupta', valuation: 'Undisclosed', thesis: 'Premium D2C food brands scaling offline', comparable: 'Country Delight' }
        },
        {
            lead: true,
            tag: 'MEGA ROUND',
            tagColor: 'purple',
            source: 'TechCrunch',
            sourceUrl: 'https://techcrunch.com',
            headline: '💸 Stripe Raises $8B at $95B Valuation — Series I Madness',
            subline: 'Stripe closes $8B round at $95B valuation led by Sequoia, a16z, and GIC — largest private fintech raise ever.',
            body: 'Stripe literally raised a round bigger than most companies\' entire market cap. The $95B valuation is back above their 2021 peak. Revenue at $26B, processing $1.2T in payments annually. They\'re not going IPO anytime soon — why would they when they can raise like this? The private markets are the new public markets fr.',
            time: '6:00 AM',
            vc: { stage: 'Series I', investors: 'Sequoia, a16z, GIC, Goldman Sachs', valuation: '$95B post-money', thesis: 'Dominant payment infra with embedded finance expansion', comparable: 'Adyen raised $1B at $46B (2023)' }
        },
        {
            tag: 'SERIES B',
            tagColor: 'purple',
            source: 'Inc42',
            sourceUrl: 'https://inc42.com',
            headline: '🇮🇳 Ather Energy Rival "Ultraviolette" Raises $80M Series B',
            subline: 'Ultraviolette Automotive raises $80M Series B at $420M valuation — TVS Motor leads, Zoho\'s Sridhar Vembu participates.',
            body: 'Ultraviolette\'s F77 performance EV bike is actually fire and the market noticed. TVS leading the round signals strategic intent — potential acquisition play down the line? India\'s premium EV 2W market is wide open with only Ather as real competition. Ngl this valuation seems fair for the TAM.',
            time: '7:30 AM',
            vc: { stage: 'Series B', investors: 'TVS Motor (lead), Zoho, Qualcomm Ventures', valuation: '$420M post-money', thesis: 'Premium EV 2-wheeler in India\'s under-penetrated market', comparable: 'Ather Energy raised $128M Series E at $1.3B (2025)' }
        },
        {
            tag: 'SEED',
            tagColor: 'mint',
            source: 'VCCircle',
            sourceUrl: 'https://vccircle.com',
            headline: '🌱 AI Legal-Tech Startup "NyayaAI" Raises $6M Seed',
            subline: 'NyayaAI raises $6M seed round led by Accel India — AI platform for Indian court case analysis and legal research.',
            body: 'Legal tech in India is lowkey one of the most underserved markets. 4.5 crore pending cases and most lawyers still use paper files. NyayaAI\'s LLM can analyze case law, predict outcomes, and draft petitions. Accel leading seed rounds in India vertical SaaS is their bread and butter. Smart bet fr.',
            time: '8:00 AM',
            vc: { stage: 'Seed', investors: 'Accel India (lead), Blume Ventures, Better Capital', valuation: '$30M post-money', thesis: 'AI-native legal research for India\'s 4.5Cr pending court cases', comparable: 'SpotDraft raised $26M Series A (2024) in legal tech' }
        },
        {
            tag: 'SERIES A',
            tagColor: 'purple',
            source: 'Crunchbase News',
            sourceUrl: 'https://crunchbase.com',
            headline: '🧬 Biotech Startup "Elucidata" Raises $35M Series A',
            subline: 'Elucidata raises $35M Series A from Eight Roads and Lightspeed — AI platform for drug discovery data.',
            body: 'Elucidata is building the "Snowflake for biotech" — a data platform that structures messy omics data for pharma companies. Their customers include 3 of the top 10 pharma companies globally. Drug discovery is a $2T market and the data infra layer is bussin. Eight Roads leading makes sense — they backed PharmEasy early.',
            time: '8:45 AM',
            vc: { stage: 'Series A', investors: 'Eight Roads (lead), Lightspeed India, Naukri Fund', valuation: '$180M post-money', thesis: 'Data infrastructure layer for AI-driven drug discovery', comparable: 'Benchling raised $100M Series F (2025) in life sciences data' }
        },
        {
            tag: 'SERIES C',
            tagColor: 'purple',
            source: 'PitchBook',
            sourceUrl: 'https://pitchbook.com',
            headline: '🚀 Climate-Tech "CarbonClean" Bags $150M Series C',
            subline: 'CarbonClean raises $150M Series C led by Brookfield at $800M — carbon capture tech for industrial emitters.',
            body: 'Carbon capture is having its moment and CarbonClean (India-founded, UK-HQ) is leading the charge. Their modular CCUS tech costs 50% less than legacy solutions. Brookfield leading = serious infrastructure capital behind this. The EU carbon border tax is about to make this tech mandatory. Smart money positioning early.',
            time: '7:00 AM',
            vc: { stage: 'Series C', investors: 'Brookfield (lead), Chevron Technology Ventures, Samsung', valuation: '$800M post-money', thesis: 'Low-cost modular carbon capture for heavy industry', comparable: 'Climeworks raised $650M Series F (2024) in DAC' }
        },
        {
            tag: 'FUND LAUNCH',
            tagColor: 'gold',
            source: 'Axios Pro Rata',
            sourceUrl: 'https://axios.com/pro/deals',
            headline: '🏦 Accel Closes $650M India Fund VII — Largest India VC Fund',
            subline: 'Accel raises $650M for India Fund VII — largest India-dedicated VC fund ever, targeting 25-30 investments.',
            body: 'Accel really said "we\'re going all-in on India" with a $650M war chest. This is 2x their last India fund. They\'re doubling down on vertical SaaS, AI infrastructure, and consumer tech. Prayank Swaroop (India MD) has the best seed-stage track record in the country. Flipkart, Swiggy, Freshworks — the portfolio speaks fr.',
            time: '6:30 AM',
        },
        {
            tag: 'UNICORN',
            tagColor: 'purple',
            source: 'CB Insights',
            sourceUrl: 'https://cbinsights.com',
            headline: '🦄 India Mints 3 New Unicorns in May — Total Now 118',
            subline: 'PhysicsWallah ($2.8B), Porter ($1.4B), and Perfios ($1.1B) join India unicorn club in May 2026.',
            body: 'India unicorn factory still churning fr. PW at $2.8B is the edtech exception — profitable and growing. Porter\'s logistics play at $1.4B makes sense with the intra-city delivery boom. Perfios at $1.1B is the banking infra pick — 900+ banks use their platform. The $1B valuation bar feels lowkey too low for India now.',
            time: '9:00 AM',
        },
    ],

    'regulation-patrol': [
        {
            lead: true,
            tag: 'SEBI',
            tagColor: 'slate',
            source: 'SEBI',
            sourceUrl: 'https://sebi.gov.in',
            headline: '🏛️ SEBI\'s New F&O Rules Hit Different — Margin Shock Incoming',
            subline: 'SEBI mandates 25% minimum margin for index options from July 1 + weekly expiry limited to 1 per exchange.',
            body: 'SEBI really said "retail F&O gambling ends today" no cap. The 25% margin requirement will wipe out most of the small-ticket punters who were YOLO-ing weekly options. Brokers estimate 40% volume drop in index options. Zerodha, Angel One, and Groww shares all dipped 3-5% on the news. This is honestly good for market health tho fr.',
            time: '8:00 AM',
        },
        {
            tag: 'RBI',
            tagColor: 'slate',
            source: 'RBI',
            sourceUrl: 'https://rbi.org.in',
            headline: '🏦 RBI Holds Repo Rate at 6.0% — "Wait and Watch" Mode',
            subline: 'RBI MPC votes 5-1 to hold repo rate at 6.0% — GDP growth upgraded to 7.0% for FY27.',
            body: 'RBI Governor lowkey said "economy is vibing, inflation is chill at 4.2%, why rock the boat." The GDP upgrade to 7.0% is a flex. One MPC member (Ashima Goyal) voted for a 25bps cut, but majority wants to see if the monsoon disrupts food prices. Next cut probably in August if monsoon is normal.',
            time: '10:00 AM',
        },
        {
            tag: 'SEC',
            tagColor: 'slate',
            source: 'SEC',
            sourceUrl: 'https://sec.gov',
            headline: '⚖️ SEC Approves Spot Ethereum ETF Options — Crypto Gang Wins',
            subline: 'SEC greenlights options trading on spot Ethereum ETFs — BlackRock and Fidelity ETH products eligible immediately.',
            body: 'The SEC really went from "crypto is securities fraud" to "here\'s options on ETH ETFs" in 2 years. Gary Gensler\'s replacement is actually pro-innovation. Options on ETH ETFs means institutional hedging and income strategies are now possible. ETH pumped 8% on the news. The crypto-TradFi merge continues.',
            time: '7:00 AM',
        },
        {
            tag: 'MCA',
            tagColor: 'slate',
            source: 'Mint',
            sourceUrl: 'https://livemint.com',
            headline: '📋 MCA Eases Private Company Compliance — Startup Relief',
            subline: 'MCA notification exempts private companies under ₹50 crore turnover from 12 compliance requirements.',
            body: 'The Ministry of Corporate Affairs finally doing something useful for startups ngl. Removing 12 compliance requirements for small private companies saves ₹2-4 lakh per year in CA fees alone. Annual return filing simplified, board meeting requirements relaxed. This should\'ve happened 5 years ago but we\'ll take it.',
            time: '8:30 AM',
        },
        {
            tag: 'TAX',
            tagColor: 'red',
            source: 'Economic Times',
            sourceUrl: 'https://economictimes.com',
            headline: '💰 LTCG Tax on Equity May Drop to 10% — Budget Leak?',
            subline: 'Sources suggest FM considering reduction of LTCG on equity from 12.5% to 10% in Union Budget 2026-27.',
            body: 'If this leak is real, the market is about to party hard fr. LTCG tax going from 12.5% to 10% would be a massive sentiment boost. The original hike from 10% to 12.5% in 2024 was universally hated. Dalal Street insiders say this is Finance Ministry\'s way of boosting market participation before state elections. No official confirmation yet tho.',
            time: '6:00 AM',
        },
        {
            tag: 'ESG',
            tagColor: 'mint',
            source: 'Business Standard',
            sourceUrl: 'https://business-standard.com',
            headline: '🌿 SEBI Makes BRSR Core Mandatory for Top 500 Companies',
            subline: 'SEBI mandates BRSR Core ESG reporting with limited assurance for top 500 listed companies from FY27.',
            body: 'ESG reporting in India just got real. BRSR Core means actual audited ESG metrics, not the greenwashing vibes from the old CSR reports. Companies now need third-party assurance on carbon emissions, water usage, and workforce diversity data. Big4 accounting firms are about to make a killing on this compliance wave.',
            time: '9:00 AM',
        },
    ],

    'global-dial': [
        {
            lead: true,
            tag: 'FED',
            tagColor: 'cyan',
            source: 'Bloomberg',
            sourceUrl: 'https://bloomberg.com',
            headline: '🌍 Fed Holds Rates at 4.75% — Dot Plot Shows 2 Cuts in 2026',
            subline: 'Federal Reserve keeps rates at 4.75-5.0% — median dot plot now shows 2 rate cuts by December 2026.',
            body: 'Powell really said "we\'re in no hurry" for the 47th time but the dot plot is lowkey dovish. 2 cuts by year-end means September and December are live meetings. Inflation at 2.4% is close enough to target. The market is pricing in 3 cuts tho so there\'s a disconnect. Tbh the Fed communication game needs work fr.',
            time: '2:00 AM',
        },
        {
            tag: 'INFLATION',
            tagColor: 'cyan',
            source: 'Reuters',
            sourceUrl: 'https://reuters.com',
            headline: '📉 US CPI at 2.4% — Disinflation Continues but Slowly',
            subline: 'May CPI prints at 2.4% YoY (vs 2.5% expected) — core CPI at 2.8%, services inflation still sticky.',
            body: 'The disinflation grind continues but ngl services inflation at 4.1% is still mid. Rent and healthcare costs just won\'t come down. Goods deflation is doing all the heavy lifting. The "last mile" to 2% is going to take forever. Markets rallied on the headline beat but bond yields barely moved — smart money knows the details.',
            time: '6:30 PM',
        },
        {
            tag: 'TARIFFS',
            tagColor: 'red',
            source: 'Financial Times',
            sourceUrl: 'https://ft.com',
            headline: '🚨 US Slaps 25% Tariff on EU Steel — Trade War 2.0?',
            subline: 'Trump administration imposes 25% tariff on EU steel and aluminum imports — EU threatens retaliation on US tech.',
            body: 'Here we go again fr. The US just tariffed EU steel at 25% and Brussels is threatening counter-tariffs on Apple, Google, and Amazon. This is lowkey bullish for Indian steel exporters tho — JSW and Tata Steel could grab EU market share if EU retaliates against US steel. Global trade is becoming a chess game.',
            time: '8:00 AM',
        },
        {
            tag: 'CHINA',
            tagColor: 'cyan',
            source: 'Bloomberg',
            sourceUrl: 'https://bloomberg.com',
            headline: '🇨🇳 China GDP Slows to 4.2% — Property Crisis Not Over',
            subline: 'China Q1 GDP at 4.2% misses 4.8% target — property sector still contracting at -8.3% YoY.',
            body: 'China\'s economy is giving "struggling main character" energy rn. Property sector is still a disaster — Evergrande, Country Garden, and now Vanke all in various stages of distress. Youth unemployment at 21% is a social bomb. The PBOC cut rates again but it\'s pushing on a string. India literally overtook China\'s growth rate and nobody\'s surprised anymore.',
            time: '3:30 AM',
        },
        {
            tag: 'GEOPOLITICS',
            tagColor: 'red',
            source: 'Reuters',
            sourceUrl: 'https://reuters.com',
            headline: '🌐 US-India Defense Deal: $3.8B Apache + MQ-9B Package',
            subline: 'US approves $3.8B defense sale to India — 31 MQ-9B Predator drones + 12 Apache helicopters.',
            body: 'The India-US defense corridor is getting deeper fr. $3.8B is the largest single US defense sale to India. MQ-9B drones for maritime surveillance in the Indian Ocean = China containment strategy. Defense stocks (HAL, BEL, BDL) all ripped 2-4% on the news. The strategic partnership is no longer just vibes, it\'s hardware.',
            time: '7:00 AM',
        },
        {
            tag: 'EU',
            tagColor: 'cyan',
            source: 'Financial Times',
            sourceUrl: 'https://ft.com',
            headline: '🇪🇺 ECB Cuts Rates to 3.0% — 4th Cut This Cycle',
            subline: 'ECB cuts deposit rate by 25bps to 3.0% — Euro area inflation at 1.9%, below target for first time since 2021.',
            body: 'The ECB is lowkey the most dovish central bank in the G7 rn. Inflation below 2% means they have room to cut more. The Euro dropped to $1.06 which is great for European exporters. Lagarde said more cuts coming if data cooperates. The US-EU rate differential is now 175bps — widest since 2019.',
            time: '7:45 AM',
        },
    ],

    'yield-flow': [
        {
            lead: true,
            tag: 'US BONDS',
            tagColor: 'gold',
            source: 'Bloomberg',
            sourceUrl: 'https://bloomberg.com',
            headline: '📈 US 10Y at 4.38% — The Inversion Watch Continues',
            subline: 'US 10Y yield at 4.38% vs 2Y at 4.52% — yield curve still inverted at -14bps for 24th consecutive month.',
            body: 'The most predicted recession ever still hasn\'t happened and the yield curve is still inverted lol. 24 months of inversion is a record. The 2Y-10Y spread at -14bps is narrowing tho — which historically means the recession is closer, not further. Or maybe this time IS different? Bond market said "we\'ll figure it out eventually." Ngl the signal is noisy.',
            time: '7:00 AM',
        },
        {
            tag: 'INDIA G-SEC',
            tagColor: 'gold',
            source: 'RBI',
            sourceUrl: 'https://rbi.org.in',
            headline: '🇮🇳 India 10Y G-Sec at 7.02% — JPMorgan Index Flow Effect',
            subline: 'India 10Y benchmark at 7.02% — FPI inflows of ₹18,000 crore into G-Secs post-JPMorgan index inclusion.',
            body: 'The JPMorgan index inclusion effect is real and it\'s bussin. FPIs bought ₹18,000 crore of Indian G-Secs in May alone. The 7.02% yield on the 10Y is the lowest since March 2024. RBI probably vibing — their rate cut transmission is actually working this time. Gilt funds returned 4.8% in the last 6 months fr.',
            time: '8:00 AM',
        },
        {
            tag: 'CORPORATE BONDS',
            tagColor: 'gold',
            source: 'Mint',
            sourceUrl: 'https://livemint.com',
            headline: '🏢 AAA Corporate Bond Spread at 35bps — Credit Party Mode',
            subline: 'AAA corporate bond spread over G-Sec compresses to 35bps — lowest since 2019.',
            body: 'Credit spreads are absolutely compressed rn. AAA at 35bps over govies means the market is saying "these companies are basically government-level safe." HDFC Bank and RIL bonds are trading at G-Sec+20bps which is mental. The bond market is pricing in zero default risk for quality credits. Might be complacent but the economy supports it.',
            time: '8:30 AM',
        },
        {
            tag: 'SDL',
            tagColor: 'gold',
            source: 'Economic Times',
            sourceUrl: 'https://economictimes.com',
            headline: '📊 State Dev Loans Auction — Cutoff at 7.28% for 10Y',
            subline: 'SDL auction clears at 7.28% for 10Y paper — 26bps spread over G-Sec, ₹22,000 crore raised.',
            body: 'SDLs are lowkey the best risk-adjusted fixed income trade in India. 26bps over G-Sec for state government paper is free money. Tamil Nadu and Maharashtra SDLs got the most demand. Insurance companies and PFs are lapping these up. If you\'re in debt funds, make sure your fund manager has SDL exposure fr.',
            time: '9:00 AM',
        },
        {
            tag: 'GLOBAL YIELDS',
            tagColor: 'cyan',
            source: 'Reuters',
            sourceUrl: 'https://reuters.com',
            headline: '🌐 Japan 10Y Hits 1.2% — BOJ Normalization Play Is On',
            subline: 'JGB 10Y yield at 1.2%, highest since 2011 — BOJ signals another rate hike to 0.75% in July.',
            body: 'Japan is finally joining the "positive interest rate" club after 25 years and the JGB market is adjusting in real-time. 1.2% doesn\'t sound like much but for Japan this is a seismic shift. Japanese investors selling foreign bonds to buy domestic = pressure on US Treasuries. The yen carry trade unwind risk is lowkey the biggest tail risk in global markets rn.',
            time: '4:00 AM',
        },
    ],

    'smart-reads': [
        {
            lead: true,
            tag: 'MUST READ',
            tagColor: 'rose',
            source: 'a16z Blog',
            sourceUrl: 'https://a16z.com/ai-agents-will-eat-saas',
            headline: '📚 a16z: "Why AI Agents Will Eat SaaS" — The Future Is Agentic',
            subline: 'a16z publishes landmark essay arguing AI agents will replace traditional SaaS — $600B market disruption thesis.',
            body: 'This a16z piece is genuinely the most important thing you\'ll read this month, no cap. Their thesis: AI agents don\'t just automate workflows within SaaS tools — they REPLACE the SaaS tools entirely. Why pay $50/seat/month for a CRM when an AI agent can manage customer relationships natively? The SaaS model (seats × price) dies when agents work 24/7 without seats. They estimate 40% of current SaaS revenue is vulnerable to agent disruption by 2030. Every SaaS CEO should be losing sleep over this. Period.',
            time: '6:00 AM',
        },
        {
            tag: 'DEEP DIVE',
            tagColor: 'rose',
            source: 'Money Stuff (Bloomberg)',
            sourceUrl: 'https://bloomberg.com/opinion/authors/ARbTQlRLxRc/matthew-s-levine',
            headline: '✍️ Matt Levine: "The Private Credit Bubble Nobody Sees"',
            subline: 'Matt Levine\'s latest explores the $1.7T private credit market and why mark-to-market opacity is the next systemic risk.',
            body: 'Levine does what Levine does best — makes complex financial plumbing entertaining. The private credit market grew from $400B to $1.7T in 5 years and NOBODY can see the real marks. Unlike public bonds, private credit NAVs are "manager-estimated" which is a fancy way of saying "vibes-based." If rates stay higher for longer, some of these loans are underwater but the marks won\'t show it until a fund tries to liquidate. Read the whole thing fr.',
            time: '7:00 AM',
        },
        {
            tag: 'RESEARCH',
            tagColor: 'rose',
            source: 'McKinsey Insights',
            sourceUrl: 'https://mckinsey.com/insights',
            headline: '🔬 McKinsey: India\'s $450B Digital Economy by 2030',
            subline: 'McKinsey Global Institute projects India\'s digital economy at $450B by 2030 — 5x growth from 2024 levels.',
            body: 'McKinsey just dropped a 140-page report on India\'s digital economy and the numbers are absolutely unreal. UPI processing $28T annually by 2030. Digital lending at $350B. SaaS exports at $50B. E-commerce GMV at $200B. The India Stack (Aadhaar + UPI + ONDC + Account Aggregator) is a genuine competitive moat no other country has. If you\'re not investing in India digital, you\'re ngmi.',
            time: '8:00 AM',
        },
        {
            tag: 'VC ESSAY',
            tagColor: 'purple',
            source: 'First Round Review',
            sourceUrl: 'https://review.firstround.com',
            headline: '📝 First Round: "How to Build a $100M ARR Company in 2026"',
            subline: 'First Round Review interviews 12 founders who crossed $100M ARR — the playbook has fundamentally changed.',
            body: 'The old playbook of "raise huge, blitzscale, figure out unit economics later" is dead. First Round interviewed 12 recent $100M ARR companies and the new playbook is: ship fast with AI, keep teams under 100 people, reach profitability by Series B, and let the product sell itself. The average $100M ARR company in 2026 has 73 employees vs 450 in 2019. AI is the leverage multiplier. If you\'re a founder, this is your required reading.',
            time: '9:00 AM',
        },
        {
            tag: 'VC ESSAY',
            tagColor: 'purple',
            source: 'First Round Review',
            sourceUrl: 'https://review.firstround.com',
            headline: 'First Round: How to Build a $100M ARR Company in 2026',
            subline: 'First Round interviews 12 founders who crossed $100M ARR — the playbook has fundamentally changed.',
            body: 'The old playbook of raise huge, blitzscale, figure out unit economics later is dead. First Round interviewed 12 recent $100M ARR companies — the new formula: ship fast with AI, keep teams under 100, reach profitability by Series B. Average $100M ARR company in 2026 has 73 employees vs 450 in 2019.',
            time: '9:00 AM',
        },
    ],

    // ==================== IB TRANSACTIONS & DEALS ====================
    'ib-transactions': [
        {
            lead: true,
            dealType: 'M&A',
            dealStatus: 'signed',
            dealValue: '$4.2B',
            acquirer: 'Reliance Industries (Viacom18)',
            target: 'Havas Group',
            tag: 'CROSS-BORDER M&A',
            tagColor: 'gold',
            source: 'Bloomberg',
            sourceUrl: 'https://bloomberg.com',
            headline: 'Reliance–Havas: India\'s Largest Cross-Border Media Acquisition',
            subline: 'Mukesh Ambani\'s Reliance acquires Havas Group from Vivendi at $4.2B enterprise value, creating an integrated media-and-advertising powerhouse across 100+ markets.',
            body: 'The deal gives RIL\'s JioCinema-Viacom18 stack a global ad-tech layer and creative backbone overnight. Havas operates in 100+ markets with $2.8B annual revenue. Implied EV/Revenue of 1.5x — lean for media but rich for an emerging-market buyer. Goldman Sachs and AZB & Partners advised RIL; JPMorgan and Linklaters advised Vivendi.',
            advisors: { buy: 'Goldman Sachs, AZB & Partners', sell: 'JPMorgan, Linklaters' },
            metrics: { evRevenue: '1.5x', evEbitda: '9.2x', premiumLTP: 'N/A', structure: 'Cash + Equity Swap' },
            time: '6:30 AM',
        },
        {
            dealType: 'BLOCK DEAL',
            dealStatus: 'closed',
            dealValue: '₹4,100 Cr',
            acquirer: 'HDFC MF, SBI MF',
            target: 'Swiggy (SoftBank Exit)',
            tag: 'BLOCK DEAL',
            tagColor: 'gold',
            source: 'Economic Times',
            sourceUrl: 'https://economictimes.com',
            headline: 'SoftBank Exits Swiggy: ₹4,100 Cr Block at ₹382/Share',
            subline: 'Lock-up expiry triggers SoftBank\'s partial exit at ₹382, 3.7% discount to market. Domestic MFs absorb the block.',
            body: 'SoftBank offloaded 4.2% of Swiggy via accelerated book build after lock-in period expired. HDFC MF (₹1,850 Cr) and SBI MF (₹1,100 Cr) took anchor positions. Swiggy remains 28% above IPO price. Kotak Investment Banking ran the book.',
            advisors: { buy: 'Kotak Investment Banking', sell: 'Morgan Stanley (SoftBank adviser)' },
            metrics: { discountLTP: '3.7%', stockPostDeal: '-3.7%', lockupPeriod: '180 days', floatAdded: '4.2%' },
            time: '7:15 AM',
        },
        {
            dealType: 'PE BUYOUT',
            dealStatus: 'signed',
            dealValue: '₹7,200 Cr',
            acquirer: 'KKR India',
            target: 'Healthium Medtech',
            tag: 'TAKE-PRIVATE',
            tagColor: 'gold',
            source: 'Reuters',
            sourceUrl: 'https://reuters.com',
            headline: 'KKR\'s ₹7,200 Cr Take-Private Bid on Healthium Medtech',
            subline: 'KKR India proposes to delist Healthium at ₹228/share — 34% premium to 6-month VWAP. Board recommends acceptance.',
            body: 'KKR plans to merge Healthium with its existing healthcare portfolio (HCP) post-privatisation and re-list within 3 years. The buyout values Healthium at 18x EV/EBITDA. SEBI\'s delisting rules require 90% shareholder acceptance for success. Rothschild & Co advised KKR; Jefferies advised the Healthium board.',
            advisors: { buy: 'Rothschild & Co, Cyril Amarchand', sell: 'Jefferies India, AZB & Partners' },
            metrics: { evEbitda: '18x', premiumVWAP: '34%', targetAcceptance: '90%', closingETA: 'Q3 2026' },
            time: '8:00 AM',
        },
        {
            dealType: 'DEBT ISSUANCE',
            dealStatus: 'closed',
            dealValue: '$1.5B',
            acquirer: 'Global Bond Investors',
            target: 'Adani Ports & SEZ',
            tag: 'HIGH YIELD BOND',
            tagColor: 'gold',
            source: 'Financial Times',
            sourceUrl: 'https://ft.com',
            headline: 'Adani Ports Prices $1.5B Dollar Bond at 6.75%',
            subline: '10-year dollar bond 4x oversubscribed — signal that global credit appetite for Indian infra paper is firmly back.',
            body: '$1.5B at 6.75% coupon, 10-year maturity. Order book hit $6.2B — 4.1x covered. US accounts took 48%, Europe 28%, Asia 24%. Proceeds earmarked for port capex and refinancing of existing 2024 bonds. Citi, JPMorgan, and Standard Chartered ran the books.',
            advisors: { buy: 'Citi, JPMorgan, Standard Chartered', sell: 'N/A' },
            metrics: { coupon: '6.75%', tenor: '10 years', oversubscription: '4.1x', useOfProceeds: 'Capex + Refi' },
            time: '9:00 AM',
        },
        {
            dealType: 'QIP',
            dealStatus: 'closed',
            dealValue: '₹8,500 Cr',
            acquirer: 'Institutional Investors',
            target: 'Zomato Ltd',
            tag: 'QIP',
            tagColor: 'gold',
            source: 'Mint',
            sourceUrl: 'https://livemint.com',
            headline: 'Zomato Raises ₹8,500 Cr via QIP at ₹224/Share',
            subline: 'Qualified Institutional Placement priced at 2% discount. Funds earmarked for Hyperpure scaling and logistics network.',
            body: 'Zomato\'s QIP was 3.8x oversubscribed with anchor allotment to Fidelity, GIC Singapore, and Axis MF. ₹5,000 Cr goes to Hyperpure (B2B food supply), ₹2,000 Cr to logistics, ₹1,500 Cr as general corporate purpose. Kotak Equities and Goldman Sachs managed the offering.',
            advisors: { buy: 'Kotak Equities, Goldman Sachs', sell: 'N/A' },
            metrics: { discountLTP: '2%', oversubscription: '3.8x', dilution: '2.1%', allocation: 'FII 72%, DII 28%' },
            time: '10:00 AM',
        },
        {
            dealType: 'PE EXIT',
            dealStatus: 'closed',
            dealValue: '₹3,200 Cr',
            acquirer: 'Public Market Buyers',
            target: 'Hexaware Technologies (Carlyle Exit)',
            tag: 'OFS / PE EXIT',
            tagColor: 'gold',
            source: 'CNBC-TV18',
            sourceUrl: 'https://cnbctv18.com',
            headline: 'Carlyle Sells ₹3,200 Cr Hexaware Stake via OFS',
            subline: 'Carlyle reduces Hexaware stake from 28% to 19% post-IPO. Price band ₹790–800. HNIs and FIIs absorb 85% of the offer.',
            body: 'Carlyle\'s second sell-down since Hexaware\'s January IPO. The OFS was priced at ₹800 — flat to market. Retail oversubscription 2.4x; FII anchor allocation at ₹795. Carlyle still holds 19% and is locked in for 90 days. ICICI Securities and Citi ran the OFS.',
            advisors: { buy: 'ICICI Securities, Citi', sell: 'N/A (Carlyle selling shareholder)' },
            metrics: { discountLTP: '0%', oversubscription: '2.4x', stakePostDeal: '19%', remainingLockup: '90 days' },
            time: '11:00 AM',
        },
        {
            dealType: 'RIGHTS ISSUE',
            dealStatus: 'announced',
            dealValue: '₹4,000 Cr',
            acquirer: 'Existing Shareholders',
            target: 'Paytm (One97 Communications)',
            tag: 'RIGHTS ISSUE',
            tagColor: 'gold',
            source: 'The Hindu BusinessLine',
            sourceUrl: 'https://thehindubusinessline.com',
            headline: 'Paytm Announces ₹4,000 Cr Rights Issue at 1:4 Ratio',
            subline: 'Rights priced at ₹385 — 18% discount to CMP. Proceeds to fund UPI infrastructure expansion and buyback of ESOP obligations.',
            body: 'Paytm\'s board approved the rights issue at 1 right share for every 4 held, priced at ₹385 vs CMP ₹472. The 18% discount is aggressive. Softbank (19.6% holder) has indicated intent to subscribe. Proceeds split: ₹2,200 Cr for payment infra, ₹1,200 Cr for ESOP buyback, ₹600 Cr for working capital.',
            advisors: { buy: 'N/A (rights offering)', sell: 'N/A' },
            metrics: { ratio: '1:4', discountCMP: '18%', expectedClose: 'July 2026', expectedDilution: '25%' },
            time: '12:00 PM',
        },
        {
            dealType: 'GDR OFFERING',
            dealStatus: 'announced',
            dealValue: '$800M',
            acquirer: 'International Investors',
            target: 'Tata Motors Ltd',
            tag: 'GDR OFFERING',
            tagColor: 'gold',
            source: 'Bloomberg',
            sourceUrl: 'https://bloomberg.com',
            headline: 'Tata Motors Files $800M GDR Offering on London Stock Exchange',
            subline: 'GDRs priced at $18.50 each, representing 2 ordinary shares. Proceeds earmarked for JLR EV transition capex.',
            body: 'Tata Motors is tapping international capital markets to fund Jaguar Land Rover\'s electrification roadmap. The $800M GDR offering on LSE is structured as new shares — 4.1% dilution. Goldman Sachs and Barclays are joint global coordinators. JLR targets 50% EV mix by FY28, requiring $5B in total capex.',
            advisors: { buy: 'Goldman Sachs, Barclays', sell: 'N/A' },
            metrics: { gdrPrice: '$18.50 / 2 shares', dilution: '4.1%', exchange: 'London Stock Exchange', useOfProceeds: 'JLR EV Capex' },
            time: '1:00 PM',
        },
    ],
};

// ==================== READING ROOM DATA ====================
const READING_ROOM = [
    {
        title: 'Inc42: The Latest Indian Startup Ecosystem Trends',
        source: 'Inc42 (LinkedIn)',
        url: 'https://www.linkedin.com/company/inc42/posts/?feedView=all',
        readTime: '5 min',
        why: 'Top source for tracking early-stage funding and regulatory shifts in India.',
    },
    {
        title: 'Sajith Pai: Micro-VC and Consumer Tech Insights',
        source: 'Sajith Pai (Blume Ventures)',
        url: 'https://www.linkedin.com/in/sajithpai/',
        readTime: '8 min',
        why: 'The absolute best frameworks for understanding the Indus Valley playbook.',
    },
    {
        title: 'Viestories: Untold Startup Narratives',
        source: 'Viestories (LinkedIn)',
        url: 'https://www.linkedin.com/company/viestories/posts/',
        readTime: '6 min',
        why: 'Great coverage of bootstrapped and regional startup success stories.',
    },
    {
        title: 'Aditya Grover: Market Microstructure & Trading',
        source: 'Aditya Grover (LinkedIn)',
        url: 'https://www.linkedin.com/in/adityagrover24/',
        readTime: '7 min',
        why: 'Deep dives into derivatives, algorithmic trading, and market anomalies.',
    },
    {
        title: 'PrivateCircle: Private Market Valuations & Data',
        source: 'PrivateCircle (LinkedIn)',
        url: 'https://www.linkedin.com/company/privatecircle/posts/',
        readTime: '4 min',
        why: 'Unmatched data on secondary transactions and private market cap tables.',
    },
    {
        title: 'YourStory: Founders and Fundamentals',
        source: 'YourStory (LinkedIn)',
        url: 'https://www.linkedin.com/company/yourstory-com/posts/',
        readTime: '5 min',
        why: 'The OG chronicle of Indian entrepreneurship. Great for founder interviews.',
    },
    {
        title: 'ValleyNxt Ventures: Early Stage Deal Flow',
        source: 'ValleyNxt Ventures (LinkedIn)',
        url: 'https://www.linkedin.com/company/valleynxtventures/posts/',
        readTime: '4 min',
        why: 'Insights on seed-stage valuations and emerging tech sectors.',
    },
    {
        title: 'Rahul Mathur: Insurtech and Fintech Deep Dives',
        source: 'Rahul Mathur (BimaPe/Verak)',
        url: 'https://www.linkedin.com/in/rahul-jaideep-mathur/',
        readTime: '6 min',
        why: 'Raw, unfiltered realities of building fintech and insurtech in India.',
    },
    {
        title: 'Better Capital: Pre-Seed Thesis and Syndicate Updates',
        source: 'Better Capital (LinkedIn)',
        url: 'https://www.linkedin.com/in/better/',
        readTime: '5 min',
        why: "Vaibhav Domkundwar's thesis on where the next companies are built.",
    },
    {
        title: 'Dilip EVS: Banking and Payments Infrastructure',
        source: 'Dilip EVS (LinkedIn)',
        url: 'https://www.linkedin.com/in/dilipevs/',
        readTime: '7 min',
        why: 'Incredible breakdowns of UPI, payment aggregators, and RBI guidelines.',
    },

    {
        title: 'The Death of the Advisory Model: How AI is Restructuring Investment Banking',
        source: 'Harvard Business Review',
        url: 'https://hbr.org',
        readTime: '14 min',
        why: 'The best framing on how AI agents will commoditise pitch books and what survives.',
    },
    {
        title: 'Inside the India PE Secondaries Boom: Why LPs Are Selling at Par',
        source: 'Preqin',
        url: 'https://preqin.com',
        readTime: '9 min',
        why: 'India PE liquidity crunch is creating a secondaries wave — useful for understanding exit dynamics.',
    },
    {
        title: 'Ben Horowitz: \"The Most Important Lesson I Learned from Building Andreessen Horowitz\"',
        source: 'a16z Blog',
        url: 'https://a16z.com',
        readTime: '11 min',
        why: 'On building firm culture in the GP/LP context. Applicable to any fund structure.',
    },
    {
        title: 'The Carry Trade Unwind: How EM Debt Blowups Actually Happen',
        source: 'Morgan Stanley Research',
        url: 'https://morganstanley.com',
        readTime: '7 min',
        why: 'Essential reading for understanding the yen-carry unwind mechanism and its EM contagion path.',
    },
    {
        title: 'Aswath Damodaran: \"Narrative and Numbers — Valuing Stories as a DCF Input\"',
        source: 'Musings on Markets',
        url: 'https://aswathdamodaran.blogspot.com',
        readTime: '18 min',
        why: 'Damodaran\'s framework for bridging qualitative story to quantitative model — required for IB analysts.',
    },
    {
        title: 'How Sovereign Wealth Funds Are Reshaping the GP Landscape in Asia',
        source: 'Institutional Investor',
        url: 'https://institutionalinvestor.com',
        readTime: '10 min',
        why: 'GIC, Temasek, ADIA are now acting like GPs — implications for co-invest and deal flow.',
    },
    {
        title: 'India\'s GIFT City: Why Every Global Bank Is Setting Up an IFSC Desk',
        source: 'Bloomberg Markets',
        url: 'https://bloomberg.com',
        readTime: '6 min',
        why: 'GIFT City is the most underappreciated regulatory arbitrage in Indian finance right now.',
    },
];
